lzo_compress-objs := lzo1x_compress.o
lzo_compress_rle-objs := lzo1x_compress_rle.o
lzo_decompress-objs := lzo1x_decompress_safe.o

obj-$(CONFIG_LZO_COMPRESS) += lzo_compress.o
obj-$(CONFIG_LZO_COMPRESS) += lzo_compress_rle.o
obj-$(CONFIG_LZO_DECOMPRESS) += lzo_decompress.o
