#!/bin/bash
set -e

KERNEL_DIR="$(pwd)"
ANYKERNEL_DIR="${KERNEL_DIR}/AnyKernel3"
OUT_DIR="${KERNEL_DIR}/out"
BUILD_LOG_FILE="${BUILD_LOG_FILE:-${KERNEL_DIR}/build.log}"

setup_build_log() {
    if [ "${BUILD_LOG_INITIALIZED:-0}" = "1" ]; then
        return
    fi

    mkdir -p "$(dirname "$BUILD_LOG_FILE")"
    : > "$BUILD_LOG_FILE"

    exec > >(tee -a "$BUILD_LOG_FILE") 2>&1
    export BUILD_LOG_INITIALIZED=1

    echo "[*] Build log: ${BUILD_LOG_FILE}"
    echo "[*] Started:   $(date '+%Y-%m-%d %H:%M:%S %Z')"
}

setup_build_log

# Keep Clang LTO builds stable on large core-count machines.
# Override with BUILD_JOBS=<n> when you intentionally want a different level.
get_build_jobs() {
    local jobs="${BUILD_JOBS:-4}"

    if ! [[ "$jobs" =~ ^[1-9][0-9]*$ ]]; then
        echo "[!] Invalid BUILD_JOBS='$jobs', falling back to 4"
        jobs=4
    fi

    printf '%s\n' "$jobs"
}

# Versioning
KERNEL_VERSION="v1.0"

# Configuration
BASE_CONFIG="sdm670-perf_defconfig"
XIAOMI_CONFIGS="xiaomi/sdm710-common.config xiaomi/grus.config"

# ── Toolchain Selection ─────────────────────────────────────────────
# CLANG_OPT: empty = GCC (default), "clang" = Clang extreme optimization
CLANG_OPT=""

# ╔═══════════════════════════════════════════════════════════════════╗
# ║  EXTREME CLANG CONFIG — Toggle switches                         ║
# ║  Set to 1 = enabled, 0 = disabled                               ║
# ║  Default: maximum performance (security/debug OFF)               ║
# ╚═══════════════════════════════════════════════════════════════════╝

# ── LTO ──
CONF_LTO=1                     # Full LTO via gold + LLVMgold.so

# ── Performance features ──
CONF_JUMP_LABEL=1               # Static keys: NOPs instead of branches
CONF_DEADLINE_IO=1              # Deadline I/O scheduler (optimal for flash/UFS)

# ── Disable debug overhead ──
CONF_DISABLE_DEBUG=1            # Strip all debug: DEBUG_INFO, SLUB_DEBUG, etc.
CONF_DISABLE_FRAME_POINTER=1   # No frame pointer (~2% perf, less reliable oops)
CONF_DISABLE_SCHEDSTATS=1      # No scheduler statistics

# ── Spectre/Meltdown mitigations ──
CONF_DISABLE_KPTI=1            # KPTI off (A75 not vulnerable, 5-30% syscall gain)
CONF_DISABLE_SPECTRE=1         # Spectre v2/v4/BHB off (firmware handles it)

# ── CPU errata (SDM710 = A75+A55 only) ──
CONF_DISABLE_IRRELEVANT_ERRATA=1  # Disable A53/A57/A72/A76/Cavium/QDF2400 errata

# ── Tracing & Logging mitigations ──
CONF_DISABLE_TRACING=1          # Disable PROFILING, IPC Logging, Trace packets
CONF_DISABLE_CORESIGHT=1        # Disable ARM CoreSight HW tracing
CONF_DISABLE_EXTRA_LOGGING=1    # Disable extra driver logging (SCSI, SPMI, MMC, SDE)

# ── Security hardening ──
CONF_WEAKEN_SECURITY=1          # Downgrade/disable non-essential security features
                                # (stackprotector→regular, no fortify, no usercopy, etc.)

# ════════════════════════════════════════════════════════════════════

generate_extreme_config() {
    local cfg="arch/arm64/configs/extreme_clang.config"
    cat > "$cfg" << 'HEADER'
# ┌─────────────────────────────────────────────────────────────────┐
# │  AUTO-GENERATED by build.sh — do not edit directly!            │
# │  Change the CONF_* toggles at the top of build.sh instead.    │
# └─────────────────────────────────────────────────────────────────┘
# Extreme Clang Optimization Config for SDM710 (Kryo 360 / Cortex-A75+A55)
HEADER

    # ── LTO ──
    if [ "$CONF_LTO" = 1 ]; then
        cat >> "$cfg" << 'EOF'

# ── LTO (Full LTO via gold + LLVMgold.so) ──
CONFIG_LTO_CLANG=y
# CONFIG_LD_DEAD_CODE_DATA_ELIMINATION is not set
EOF
    fi

    # ── LSE atomics (always off — broken with Clang on 4.9) ──
    cat >> "$cfg" << 'EOF'

# ── ARMv8.2-A: LSE atomics broken with Clang on kernel 4.9 ──
# CONFIG_ARM64_LSE_ATOMICS is not set
EOF

    # ── Performance features ──
    if [ "$CONF_JUMP_LABEL" = 1 ]; then
        cat >> "$cfg" << 'EOF'

# ── Static Keys (JUMP_LABEL) ──
CONFIG_JUMP_LABEL=y
EOF
    fi

    if [ "$CONF_DEADLINE_IO" = 1 ]; then
        cat >> "$cfg" << 'EOF'

# ── I/O Scheduler: deadline for flash/UFS ──
CONFIG_DEFAULT_DEADLINE=y
# CONFIG_DEFAULT_CFQ is not set
# CONFIG_DEFAULT_NOOP is not set
EOF
    fi

    # ── Disable debug ──
    if [ "$CONF_DISABLE_SCHEDSTATS" = 1 ]; then
        echo "" >> "$cfg"
        echo "# CONFIG_SCHEDSTATS is not set" >> "$cfg"
    fi

    if [ "$CONF_DISABLE_FRAME_POINTER" = 1 ]; then
        echo "" >> "$cfg"
        echo "# CONFIG_FRAME_POINTER is not set" >> "$cfg"
    fi

    if [ "$CONF_DISABLE_DEBUG" = 1 ]; then
        cat >> "$cfg" << 'EOF'

# ── Debug bloat disabled ──
# CONFIG_DEBUG_INFO is not set
# CONFIG_DEBUG_ALIGN_RODATA is not set
# NOTE: CONFIG_DEBUG_FS=y is intentionally KEPT enabled.
#   Reason: Qualcomm MSM DRM/SDE/DSI display pipeline hard-depends on debugfs:
#   - msm_drv.c::msm_drm_bind() creates debug_root via debugfs_create_dir()
#   - dsi_display.c::dsi_display_debugfs_init() creates per-display debugfs entries
#   - dsi_ctrl.c::dsi_ctrl_debugfs_init() creates per-controller debugfs entries
#   All three treat debugfs creation failure as fatal (IS_ERR_OR_NULL → goto fail).
#   Additionally, FTRACE (needed for KSU kprobes) force-selects DEBUG_FS via Kconfig
#   'select' mechanism, which cannot be overridden by config fragments.
#   Tested: DEBUG_FS=n causes black screen on boot (display never initializes).
#   Impact: minimal (~40KB overhead, debugfs dir is nearly empty with debug consumers off)
# CONFIG_REGMAP_ALLOW_WRITE_DEBUGFS is not set
# CONFIG_QMP_DEBUGFS_CLIENT is not set
# CONFIG_SLUB_DEBUG is not set
# CONFIG_SCHED_DEBUG is not set
# CONFIG_PM_DEBUG is not set
# CONFIG_DEBUG_PREEMPT is not set
# CONFIG_DEBUG_SPINLOCK is not set
# CONFIG_DEBUG_MUTEXES is not set
# CONFIG_DEBUG_ATOMIC_SLEEP is not set
# CONFIG_DEBUG_LIST is not set
# CONFIG_DEBUG_KMEMLEAK is not set
# CONFIG_PROVE_LOCKING is not set
# CONFIG_LOCKDEP is not set
# CONFIG_SOFTLOCKUP_DETECTOR is not set
# CONFIG_HARDLOCKUP_DETECTOR is not set
# CONFIG_DETECT_HUNG_TASK is not set
# CONFIG_CPU_FREQ_SWITCH_PROFILER is not set
# CONFIG_TRACER_PKT is not set
# CONFIG_NETFILTER_XT_TARGET_TRACE is not set
EOF
    fi

    # ── KPTI / Spectre ──
    if [ "$CONF_DISABLE_KPTI" = 1 ]; then
        cat >> "$cfg" << 'EOF'

# ── KPTI disabled (A75 not vulnerable to Meltdown) ──
# CONFIG_UNMAP_KERNEL_AT_EL0 is not set
EOF
    fi

    if [ "$CONF_DISABLE_SPECTRE" = 1 ]; then
        cat >> "$cfg" << 'EOF'

# ── Spectre mitigations disabled (firmware handles it) ──
# CONFIG_HARDEN_BRANCH_PREDICTOR is not set
# CONFIG_ARM64_SSBD is not set
# CONFIG_MITIGATE_SPECTRE_BRANCH_HISTORY is not set
EOF
    fi

    # ── CPU errata ──
    if [ "$CONF_DISABLE_IRRELEVANT_ERRATA" = 1 ]; then
        cat >> "$cfg" << 'EOF'

# ── CPU errata disabled (not present on SDM710 A75+A55) ──
# A53
# CONFIG_ARM64_ERRATUM_826319 is not set
# CONFIG_ARM64_ERRATUM_827319 is not set
# CONFIG_ARM64_ERRATUM_824069 is not set
# CONFIG_ARM64_ERRATUM_819472 is not set
# CONFIG_ARM64_ERRATUM_845719 is not set
# CONFIG_ARM64_ERRATUM_843419 is not set
# A57
# CONFIG_ARM64_ERRATUM_832075 is not set
# A57/A72
# CONFIG_ARM64_ERRATUM_1742098 is not set
# A76
# CONFIG_ARM64_ERRATUM_1188873 is not set
# Cavium ThunderX
# CONFIG_CAVIUM_ERRATUM_22375 is not set
# CONFIG_CAVIUM_ERRATUM_23154 is not set
# CONFIG_CAVIUM_ERRATUM_27456 is not set
# QDF2400 server
# CONFIG_QCOM_QDF2400_ERRATUM_0065 is not set
# KEEP: ARM64_ERRATUM_1024718 (Cortex-A55 — SDM710 silver cores)
EOF
    fi

    # ── Tracing / Logging ──
    if [ "$CONF_DISABLE_TRACING" = 1 ]; then
        cat >> "$cfg" << 'EOF'

# ── Tracing & Logging bloat disabled ──
# CONFIG_PROFILING is not set
# CONFIG_IPC_LOGGING is not set
# CONFIG_TRACER_PKT is not set
# CONFIG_MSM_TZ_LOG is not set
# CONFIG_QTI_RPM_STATS_LOG is not set
# CONFIG_QMP_DEBUGFS_CLIENT is not set
EOF
    fi

    if [ "$CONF_DISABLE_CORESIGHT" = 1 ]; then
        cat >> "$cfg" << 'EOF'

# ── CoreSight HW Tracing disabled ──
# CONFIG_CORESIGHT is not set
EOF
    fi

    if [ "$CONF_DISABLE_EXTRA_LOGGING" = 1 ]; then
        cat >> "$cfg" << 'EOF'

# ── Extra Driver Logging disabled ──
# CONFIG_SCSI_LOGGING is not set
# CONFIG_SCSI_UFSHCD_CMD_LOGGING is not set
# CONFIG_SCSI_CONSTANTS is not set
# CONFIG_DM_DEBUG is not set
# CONFIG_SPMI_MSM_PMIC_ARB_DEBUG is not set
# CONFIG_VIDEO_ADV_DEBUG is not set
# CONFIG_MSM_SDE_ROTATOR_EVTLOG_DEBUG is not set
# CONFIG_DRM_SDE_EVTLOG_DEBUG is not set
# CONFIG_MMC_PERF_PROFILING is not set
# CONFIG_MMC_TEST is not set
# CONFIG_IOMMU_DEBUG is not set
# CONFIG_IOMMU_DEBUG_TRACKING is not set
# CONFIG_IOMMU_TESTS is not set
# CONFIG_RMNET_DATA_DEBUG_PKT is not set
# CONFIG_IPC_LOGGING is not set
# CONFIG_NETFILTER_XT_TARGET_LOG is not set
# CONFIG_NETFILTER_XT_TARGET_NFLOG is not set
# CONFIG_NETFILTER_XT_MATCH_STATISTIC is not set
# CONFIG_MSM_TZ_LOG is not set
# CONFIG_QTI_RPM_STATS_LOG is not set
# CONFIG_MSM_BOOT_STATS is not set
# CONFIG_QCOM_RUN_QUEUE_STATS is not set
# CONFIG_QCOM_MEMORY_DUMP_V2 is not set
# CONFIG_QCOM_MINIDUMP is not set
# CONFIG_CPU_FREQ_STAT is not set
# CONFIG_SCHEDSTATS is not set
# CONFIG_TASKSTATS is not set
# CONFIG_TASK_XACCT is not set
# CONFIG_TASK_IO_ACCOUNTING is not set
# CONFIG_UID_SYS_STATS is not set
# CONFIG_MEMORY_STATE_TIME is not set
# CONFIG_XFRM_STATISTICS is not set
# CONFIG_KALLSYMS_ALL is not set
EOF
    fi

    # ── Security ──
    if [ "$CONF_WEAKEN_SECURITY" = 1 ]; then
        cat >> "$cfg" << 'EOF'

# ── Security hardening reduced ──
# CONFIG_CC_STACKPROTECTOR_STRONG is not set
CONFIG_CC_STACKPROTECTOR_REGULAR=y
# CONFIG_FORTIFY_SOURCE is not set
# CONFIG_HARDENED_USERCOPY is not set
# CONFIG_SECURITY_SMACK is not set
# CONFIG_INTEGRITY is not set
# CONFIG_SECURITY_PERF_EVENTS_RESTRICT is not set
# CONFIG_RANDOMIZE_BASE is not set
# CONFIG_SECURITY_SELINUX_AVC_STATS is not set
# MUST KEEP: SECURITY, SELINUX, AUDIT, SECCOMP (Android requires these)
EOF
    fi

    echo "[*] Generated $cfg ($(wc -l < "$cfg") lines)"
}

setup_gcc_toolchain() {
    MAKE_FLAGS=(
        O="${OUT_DIR}"
        ARCH=arm64
        CROSS_COMPILE=aarch64-linux-gnu-
        KBUILD_BUILD_HOST="${KBUILD_BUILD_HOST:-cursor}"
    )
    echo "[*] Toolchain: GCC ($(aarch64-linux-gnu-gcc --version | head -1))"
}

setup_clang_toolchain() {
    # ── SDM710 Micro-Architecture: Kryo 360 ────────────────────────
    # Kryo 360 Gold = Cortex-A75 (2x, big cores, ARMv8.2-A)
    # Kryo 360 Silver = Cortex-A55 (6x, LITTLE cores, ARMv8.2-A)
    # Tune for A75 (prime/big core handles latency-critical paths)
    #
    # -mcpu=cortex-a75  : Pipeline scheduling tuned for A75 OoO engine
    #                     Sets PrefLoopAlignment=Align(16), optimal L1i fetch
    # -march=armv8.2-a  : Full ARMv8.2-A ISA (implied by cortex-a75)
    #   +crypto         : HW AES/SHA — accelerates fscrypt, dm-crypt, WireGuard
    #   +dotprod        : Dot-product instructions for vectorized operations
    # -mtune=cortex-a75 : Instruction latency model for the big core

    # ── Target flags ──
    # -mcpu=cortex-a75  : Pipeline scheduling + instruction latency for A75 OoO
    # +crypto           : HW AES/SHA for fscrypt, dm-crypt, WireGuard
    # Note: +dotprod omitted — guarded by -mgeneral-regs-only anyway,
    #       and some Kryo 360 steppings may not advertise it to EL1
    local TARGET_FLAGS="-mcpu=cortex-a75+crypto -mtune=cortex-a75"

    # ── Optimization flags ──
    # -O3           : Aggressive inlining, loop unrolling, vectorization
    #                 (appended after Makefile's -O2; Clang uses the last one)
    # -faddrsig     : Emit address-significance table (harmless metadata)
    #
    # ── Polly polyhedral loop optimizer ──
    # -mllvm -polly                      : Enable Polly's advanced loop transformations
    # -mllvm -polly-vectorizer=stripmine : Strip-mine outer loops for vectorizer
    # -mllvm -polly-run-dce              : Run dead code elimination after Polly
    # -mllvm -polly-process-unprofitable : Optimize even "unprofitable" loops (we want max perf)
    #
    # ── LLVM backend tuning ──
    # -mllvm --enable-gvn-hoist           : Hoist common expressions out of branches
    # -mllvm --inline-threshold=600       : More aggressive inlining (default=225)
    local OPT_FLAGS="-O3 -faddrsig"

    # ── Clang frontend optimizations ──
    # NOTE: -fwhole-program-vtables, -fvirtual-function-elimination, -fforce-emit-vtables
    # are in Makefile LTO section (require -flto at frontend check time)
    OPT_FLAGS+=" -fmerge-all-constants"
    OPT_FLAGS+=" -ffinite-loops"
    OPT_FLAGS+=" -fstrict-enums"

    # ── Polly loop optimizer ──
    OPT_FLAGS+=" -mllvm -polly"
    OPT_FLAGS+=" -mllvm -polly-vectorizer=stripmine"
    OPT_FLAGS+=" -mllvm -polly-process-unprofitable"
    OPT_FLAGS+=" -mllvm -polly-run-dce"
    # NOTE: polly-loopfusion-greedy, polly-register-tiling, polly-2nd-level-tiling
    # crash Clang 22 on traps.c, mballoc.c, ipc_logging.c (SIGSEGV)

    # ── GVN & value optimization ──
    OPT_FLAGS+=" -mllvm --enable-gvn-hoist"
    # NOTE: --enable-gvn-sink triggers CorrelatedValuePropagation crash in Clang 22
    # (non-deterministic SIGSEGV on random files during parallel build)

    # ── Loop optimizations ──
    OPT_FLAGS+=" -mllvm --enable-loopinterchange"
    OPT_FLAGS+=" -mllvm --enable-loop-distribute"
    # NOTE: --enable-loop-flatten and --enable-loop-versioning-licm crash Clang 22
    # on traps.c and ext4/mballoc.c (segfault in loop analysis)

    # ── AArch64-specific backend ──
    OPT_FLAGS+=" -mllvm --aarch64-enable-global-merge"
    OPT_FLAGS+=" -mllvm --aarch64-enable-loop-data-prefetch"
    OPT_FLAGS+=" -mllvm --aarch64-enable-early-ifcvt"

    # ── Misc backend passes ──
    OPT_FLAGS+=" -mllvm --extra-vectorizer-passes"
    OPT_FLAGS+=" -mllvm --aggressive-ext-opt"
    # NOTE: --sink-common-insts breaks inline asm 'i' constraint during LTO link
    # (gold plugin fatal error: invalid operand for inline asm constraint 'i')
    OPT_FLAGS+=" -mllvm --inline-threshold=600"

    # ── Makefile override fixes ──
    # ARM64 Kconfig force-selects FRAME_POINTER → Makefile adds -fno-optimize-sibling-calls.
    # Override: tail call optimization is safe (LTO stack traces already imprecise).
    OPT_FLAGS+=" -foptimize-sibling-calls"
    # Makefile adds -fconserve-stack (GCC-only) which limits per-function stack usage.
    # Clang doesn't support -fconserve-stack or -fno-conserve-stack — it's a no-op anyway.
    # No override needed: Clang ignores it via cc-option (which silently drops unsupported flags).

    # NOTE: --gc-sections and --icf are intentionally NOT used.
    # --gc-sections deletes kernel sections referenced only by linker scripts
    # or assembly (.altinstructions, __ex_table, .pci_fixup) → instant panic.

    # ── Standalone LLVM 22 toolchain ──
    local LLVM22_DIR="$HOME/toolchains/LLVM-22.1.0-Linux-X64"
    if [ -d "$LLVM22_DIR" ]; then
        export PATH="$LLVM22_DIR/bin:$HOME/.local/bin:$PATH"
        # Fix libxml2.so.2 soname compat (Arch ships .so.16)
        export LD_LIBRARY_PATH="$LLVM22_DIR/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
    else
        # Fallback to system Clang + gold for LTO
        export PATH="$HOME/.local/bin:$PATH"
    fi

    MAKE_FLAGS=(
        O="${OUT_DIR}"
        ARCH=arm64
        LLVM=1
        LLVM_IAS=1
        CROSS_COMPILE=aarch64-linux-gnu-
        KBUILD_BUILD_HOST="${KBUILD_BUILD_HOST:-cursor}"
        "KCFLAGS=${TARGET_FLAGS} ${OPT_FLAGS}"
    )
    echo "[*] Toolchain: Clang $(clang --version | head -1)"
    echo "[*] Target:    Cortex-A75 (Kryo 360 Gold) / ARMv8.2-A+crypto"
    echo "[*] Optimize:  -O3 + Full LTO + Polly + GVN hoist + inline=600"
}

# ── Build a single variant ──────────────────────────────────────────
build_variant() {
    local variant="$1"
    local zip_name final_configs

    case "$variant" in
        nonroot)
            zip_name="Sawit-Kernel-${KERNEL_VERSION}-SDM710-NonRoot.zip"
            final_configs="$BASE_CONFIG $XIAOMI_CONFIGS nonroot.config"
            VARIANT_SUFFIX="-sawit"
            echo ""
            echo "============================================"
            echo "[*] Variant: Non-Root (Stable/Clean)"
            echo "============================================"
            ;;
        ksun)
            zip_name="Sawit-Kernel-${KERNEL_VERSION}-SDM710-KSUNext.zip"
            final_configs="$BASE_CONFIG $XIAOMI_CONFIGS ksu_next_nosusfs.config"
            VARIANT_SUFFIX="-sawit-ksun"
            echo ""
            echo "============================================"
            echo "[*] Variant: KernelSU-Next"
            echo "============================================"
            ;;
        ksun_susfs|ksu)
            zip_name="Sawit-Kernel-${KERNEL_VERSION}-SDM710-KSUNext-susfs.zip"
            final_configs="$BASE_CONFIG $XIAOMI_CONFIGS ksu_next.config"
            VARIANT_SUFFIX="-sawit-ksun-susfs"
            echo ""
            echo "============================================"
            echo "[*] Variant: KernelSU-Next + SUSFS"
            echo "============================================"
            ;;
        *)
            echo "[!] Unknown variant: $variant"
            echo "Usage: $0 [--clang] {nonroot|ksun|ksun_susfs|all}"
            return 1
            ;;
    esac

    # Append extreme_clang.config when using Clang toolchain
    if [ -n "$CLANG_OPT" ]; then
        generate_extreme_config
        final_configs="$final_configs extreme_clang.config"
        VARIANT_SUFFIX="${VARIANT_SUFFIX}-lto"

        # Keep debugfs on for the nonroot display boot test.
        if [ "$variant" = "nonroot" ]; then
            final_configs="$final_configs nonroot_debugfs.config"
            echo "[*] Override:  DEBUG_FS enabled for nonroot test"
        fi
    fi

    # Build dynamic EXTRAVERSION: e.g. -sawit-ksun-susfs-lto
    # Use a local copy so successive variant builds don't accumulate flags
    local EXTRA="${VARIANT_SUFFIX}"
    local -a BUILD_FLAGS=("${MAKE_FLAGS[@]}" "EXTRAVERSION=${EXTRA}")
    local build_jobs
    build_jobs="$(get_build_jobs)"
    echo "[*] Version:   4.9.337${EXTRA}"
    echo "[*] Jobs:      ${build_jobs}"

    echo "[*] Cleaning previous build artifacts..."
    mkdir -p "$OUT_DIR"
    rm -f "${OUT_DIR}/arch/arm64/boot/Image.gz-dtb"
    rm -f "${OUT_DIR}/.config" # Force config regeneration

    echo "[*] Configuring kernel..."
    make "${BUILD_FLAGS[@]}" $final_configs
    make "${BUILD_FLAGS[@]}" olddefconfig

    echo "[*] Building kernel..."
    make "${BUILD_FLAGS[@]}" -j"${build_jobs}" V=0 Image.gz-dtb

    if [ -f "${OUT_DIR}/arch/arm64/boot/Image.gz-dtb" ]; then
        echo "[*] Kernel built successfully!"
        echo "[*] Packaging ${zip_name}..."
        cp "${OUT_DIR}/arch/arm64/boot/Image.gz-dtb" "${ANYKERNEL_DIR}/"
        cat "${OUT_DIR}/arch/arm64/boot/dts/qcom/sdm670.dtb" \
            "${OUT_DIR}/arch/arm64/boot/dts/qcom/sdm710.dtb" > "${ANYKERNEL_DIR}/dtb"
        cd "${ANYKERNEL_DIR}"
        rm -f AnyKernel3-*.zip
        
        if command -v 7z >/dev/null 2>&1; then
            echo "[*] Packaging with 7-Zip (Extreme zip compression)..."
            # -mx=9: Ultra compression
            # -mm=Deflate: Ensures TWRP/KSU compatibility (Deflate64 is not universally supported by Android unzip)
            # -mfb=258: Max fast bytes for Deflate
            # -mpass=15: Max passes for Deflate
            7z a -tzip -mx=9 -mm=Deflate -mfb=258 -mpass=15 "${zip_name}" * -x!.git -x!README.md -x!*placeholder > /dev/null
        else
            echo "[*] 7-Zip not found. Falling back to zip..."
            zip -q -r9 "${zip_name}" * -x .git README.md *placeholder
        fi
        
        mv "${zip_name}" "${KERNEL_DIR}/"
        cd "${KERNEL_DIR}"
        echo "[*] Done! → ${KERNEL_DIR}/${zip_name}"
    else
        echo "[!] Build failed for variant: $variant"
        return 1
    fi
}

# ── Main ────────────────────────────────────────────────────────────
# Parse --clang flag
for arg in "$@"; do
    case "$arg" in
        --clang) CLANG_OPT="clang" ;;
    esac
done

# Setup toolchain
if [ -n "$CLANG_OPT" ]; then
    setup_clang_toolchain
else
    setup_gcc_toolchain
fi

# Get variant (skip --clang flag)
VARIANT=""
for arg in "$@"; do
    case "$arg" in
        --clang) ;;
        *) VARIANT="$arg" ;;
    esac
done
VARIANT="${VARIANT:-ksun_susfs}"

if [ "$VARIANT" = "all" ]; then
    echo "========================================================"
    echo "[*] Building ALL variants: nonroot, ksun, ksun_susfs"
    echo "========================================================"
    FAILED=()
    for v in nonroot ksun ksun_susfs; do
        if build_variant "$v"; then
            echo "[✓] $v succeeded"
        else
            echo "[✗] $v failed"
            FAILED+=("$v")
        fi
    done
    echo ""
    echo "========================================================"
    if [ ${#FAILED[@]} -eq 0 ]; then
        echo "[*] All 3 variants built successfully!"
        ls -lh "${KERNEL_DIR}"/Sawit-Kernel-SDM710-*.zip
    else
        echo "[!] Failed variants: ${FAILED[*]}"
        exit 1
    fi
else
    build_variant "$VARIANT"
fi
